project:
  type: website
  output-dir: docs

website:
  title: "Kennon Holton-Tran"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: dashboard.qmd
        text: Dashboard
      - href: google-analytics.qmd
        text: Google Analytics
      - href: presentation.qmd
        text: Presentation

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    code-fold: true
    
    